const dummyUsers = [
  {
    name: '1',
    email: '1@1.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['1@1.com','2@2.com','3@3.com','4@4.com']
  },
  {
    name: '2',
    email: '2@2.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['2@2.com','1@1.com']
  },
  {
    name: '3',
    email: '3@3.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['3@3.com','1@1.com']  
  },
  {
    name: '4',
    email: '4@4.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['4@4.com','1@1.com']
  },
  {
    name: '5',
    email: '5@5.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['5@5.com']
  },
  {
    name: '6',
    email: '6@6.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['6@6.com','11@11.com']
  },
  { 
    name: '7',
    email: '7@e7.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['7@e7.com','11@11.com']
  },
  {
    name: '8',
    email: '8@8.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['8@8.com','11@11.com']
  },
  {
    name: '9',
    email: '9@9.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['9@9.com','11@11.com']
  },
  {
    name: '10',
    email: '10@10.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['10@10.com','11@11.com']
  },
  {
    name: '11',
    email: '11@11.com',
    job: 'student',
    pillar: 'atlas',
    location: 'atlanta',
    joy: 'painting',
    passion: 'art',
    secret: 'none',
    optIn: true,
    previousConnections: ['11@11.com','11@11.com'] 
  },
]

module.exports = dummyUsers